let
    sources = import ./nix/sources.nix; # sources.nix was generated by niv
    pkgs = import sources.nixpkgs { };
in
    pkgs.mkShell
{
    # nix-shell evaluates shellHooks at start
    shellHooks = ''
        alias gs="git status"
        alias gpo="git push origin"
        alias gl="git pull"
        alias ga="git add"
        alias grs="git reset"
        alias gc="git commit"
    '';

    # all packages in development environment are listed here
    buildInputs = with pkgs; [
        zsh
        ocaml
        ocamlformat
        ocamlPackages.ocaml
        ocamlPackages.dune_3
        ocamlPackages.findlib
        ocamlPackages.utop
        ocamlPackages.odoc
        ocamlPackages.ocaml-lsp
        ocamlPackages.ppx_deriving
        ocamlPackages.ppxlib
        ocamlPackages.ppx_derivers
        ocamlPackages.sexplib0
        ocamlPackages.stdlib-shims
        ocamlPackages.cppo
    ]
        #  ∗ cppo                1.8.0   [required by ppx_deriving]
        #  ∗ ocaml-compiler-libs v0.12.4 [required by ppxlib]
        #  ∗ ppx_deriving        6.1.1
        #  ∗ ppxlib              0.36.0  [required by ppx_deriving]
    ;
}
