lib: [
  "_build/install/default/lib/unisam/META"
  "_build/install/default/lib/unisam/dune-package"
  "_build/install/default/lib/unisam/elf.ml"
  "_build/install/default/lib/unisam/unisam.a"
  "_build/install/default/lib/unisam/unisam.cma"
  "_build/install/default/lib/unisam/unisam.cmi"
  "_build/install/default/lib/unisam/unisam.cmt"
  "_build/install/default/lib/unisam/unisam.cmx"
  "_build/install/default/lib/unisam/unisam.cmxa"
  "_build/install/default/lib/unisam/unisam.ml"
  "_build/install/default/lib/unisam/unisam__Elf.cmi"
  "_build/install/default/lib/unisam/unisam__Elf.cmt"
  "_build/install/default/lib/unisam/unisam__Elf.cmx"
]
libexec: [
  "_build/install/default/lib/unisam/unisam.cmxs"
]
bin: [
  "_build/install/default/bin/unisam"
]
doc: [
  "_build/install/default/doc/unisam/LICENSE"
  "_build/install/default/doc/unisam/README.md"
]
